version: "3.9"

services:
  java-app:
    container_name: java-app
    image: prueba-tecnica
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:mysql://java-db:3306/clima?useSSL=false&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=admin123456789
    depends_on:
      - java-db

  java-db:
    container_name: java-db
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456789
